Repository Vondas/Spiros, pull requests merged in 2018-06, with the labels that each got.

#25 delete legacy folders
  Controller/.gitignore
  Model/.gitignore
  Utils/.gitignore
Labels: delete folder

#28 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Docs

#29 Update README.md
  README.md
Labels: Docs

#30 Create CHANGELOG.MD
  CHANGELOG.MD
Labels: Docs

#32 Automation changelog
  .gitignore
  CACHE/06/06a59c6482e2925ddbe4bcb5090cc72a02785d1554c5298a7a0120aaeb2371ea.php
  CHANGELOG.md
  Controller/.gitignore
  Controllers/BaseController.php
  Controllers/CustomersController.php
  Controllers/IndexController.php
  Model/.gitignore
  Utils/.gitignore
  Views/customersList.html.twig
  Views/index.html
  composer.json
  config/routing.yaml
  connect.php
  index.php
  public/assets/fluid.svg
  public/assets/logo.svg
  public/css/index.css
  seed/bdd.sql
Labels: Docs, Features, Markdown

#50 wire sidebar links
  Controllers/CalendarController.php
  Controllers/ClientsController.php
  Controllers/EstimatesController.php
  Views/calendar.html.twig
  Views/clients.html.twig
  Views/estimates.html.twig
  Views/sidebar.html.twig
  config/routing.yaml
  sass/main.scss
Labels: Type: Bug

#52 Profile page
  Controllers/ProfileController.php
  Views/clients.html.twig
  Views/estimates.html.twig
  Views/header.html.twig
  Views/profile.html.twig
  config/routing.yaml
  public/assets/smiley.png
  public/styles/main.css
  public/styles/main.css.map
  sass/main.scss
  sass/pages/_userProfil.scss
Labels: Features

#54 add installation and usage instructions in readme
  README.md
Labels: Docs

#57 account creation
  Contexts/AccountContext/Account.php
  Controllers/IndexController.php
  Controllers/SignupController.php
  Repositories/UserRepository.php
  Views/login.html.twig
  config/routing.yaml
  seed/bdd.sql
Labels: Features

#60 handle customer creation and listing
  Contexts/ClientContext/Client.php
  Controllers/ClientsController.php
  Repositories/ClientRepository.php
  Views/clients.html.twig
  Views/create_profile.html.twig
  config/routing.yaml
  public/styles/main.css
  public/styles/main.css.map
  sass/pages/_listing.scss
  sass/pages/_listingDevis.scss
  seed/bdd.sql
Labels: Features

#61 handle logout
  Controllers/LogoutController.php
  Views/header.html.twig
  config/routing.yaml
  public/styles/main.css
  public/styles/main.css.map
  sass/pages/_sidebar-header.scss
Labels: Features
